title: Aleph Zero Wallet Documentation
description: Aleph Zero Wallet  is a MetaMask snap for Aleph Zero blockchain.
theme: just-the-docs

url: https://test.azero.dev

aux_links:
  Source Repository: https://github.com/bide-dev/azero-wallet

logo: "/assets/images/aleph-zero-logo.png"
favicon_ico: "/assets/images/favicon.svg"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

heading_anchors: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/bide-dev/azero-wallet"
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs
gh_edit_view_mode: "edit"
